### ISSUE TITLE
[FEAT] Minimal statusline option 

### ISSUE THREAD

**Issue by Yushi5058** [imsi32/yatline.yazi#1]
Hello, 
The plugin looks promising. I would like to suggest making a minimal option for the statusline and without the header please, for example I would just like the bottom statusline option alone to display. 
Thanks for the awesome work, 
Yushi

**Comment by DreamMaoMao** [comment]
emm...I'm the opposite of you. I just want the top

**Comment by DreamMaoMao** [comment]
I think it would be nice to have a more flexible way to customize where components are placed

**Comment by Yushi5058** [comment]
I agree, with a general minimal configuration easy to tweak to our preference

**Comment by imsi32** [comment]
My next goal is to automate the progress of placement and style of the components according to the given config. I considered that after this, I can give 3 minimal config for different needs such as both header-line and status-line, or only header-line or only status-line, so that everybody can choose the one closest to their preferences.

**Comment by Yushi5058** [comment]
> My next goal is to automate the progress of placement and style of the components according to the given config. I considered that after this, I can give 3 minimal config for different needs such as both header-line and status-line, or only header-line or only status-line, so that everybody can choose the one closest to their preferences.

Awesome, looking forward to it. Thanks !
