### ISSUE TITLE
Does not work with new nightly 0.3.3

### ISSUE THREAD

**Issue by bertradio** [imsi32/yatline.yazi#35]
The API's have changed and yatline no longer works. Any plans for an update so it will also work for version 0.4 when it comes out? Using Yazi 0.3.3 (fbf9b3d 2024-12-05)

**Comment by imsi32** [comment]
Yes, I am planning to do so.  However, I am full 2 weeks, so if it is hard to fix it needs to wait until than. I checked commits quickly but couldn't find what created issue.

Can you give me more information like error message and what version you were using before updating it?

Also, I assume problem can be related to components, can you test if removing components will fix the issue? (Note: Put at least one component so that it wouldn't use default lines and try different ones.)

**Comment by bertradio** [comment]
Sorry. Don't recall when it stopped working. But I think it worked with 0.3.0. 

I don't see any errors. I just get the prior yazi display, not yatline.

**Comment by sxyazi** [comment]
@bertradio Could you please try https://github.com/imsi32/yatline.yazi/pull/36

**Comment by bertradio** [comment]
That works. Now how do I get the modified time on the status line?

**Comment by imsi32** [comment]
Fixed with #36. Thanks for the notice.

**Comment by bertradio** [comment]
Thanks. I added the following code to display modified time.

`--- Gets the hovered file's modified date of the current active tab.
--- @return string name Current active tab's hovered file's modified date.
function Yatline.string.get:hovered_modified()
  local hovered = cx.active.current.hovered
  if hovered then
    local time = (hovered.cha.mtime or 0) // 1
    if time == 0 then
      return ''```

    elseif os.date('%Y', time) == os.date('%Y') then
      -- return tostring(os.date('%a %m/%d/%y - %H:%M', time))
      return tostring(os.date('%m/%d/%y - %H.%M', time))
    else
      return tostring(os.date('%m/%d/%y', time))
    end
  else
    return ''
  end
end
`
```
